version: '3.8'

services:
  archiso-builder:
    build:
      context: .
      dockerfile: Dockerfile.archiso
    image: scorelabs-builder:latest
    container_name: scorelabs-builder
    privileged: true
    platform: linux/amd64
    volumes:
      - ./:/scorelabs
      - ./build/output:/scorelabs/build/output
    working_dir: /scorelabs
    command: /bin/bash
    stdin_open: true
    tty: true
